-- ============================================================
-- POLYMARKET - Supabase Initial Schema
-- Safe to re-run: uses DROP IF EXISTS + CREATE IF NOT EXISTS
-- ============================================================
